theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
logo: /assets/brunochagas.png
title: Bruno Chagas
description: Computational Scientist at Irish Centre for High-End Computing, Ireland
google_analytics: 
